from django import forms

from django.shortcuts import render
class ModelFormPageMixin(object):
    _form = None
    _model = None
    def serve(self, request):
        if request.method == 'POST':
            form = self.get_form(request.POST, request.FILES)

            if form.is_valid():
                self.process_form_submission(form)
                # render the landing_page
                # TODO: It is much better to redirect to it
                return render(request, self.landing_page_template, {
                    'self': self,
                })
        else:
            form = self.get_form()

        return render(request, self.template, {
            'self': self,
            'form': form,
        })

    def get_form(self, *args, **kwargs):
        form_class = self.get_form_class()
        return form_class(*args, **kwargs)


    def get_form_class(self):
        if self._form:
            return self._form
        if self._model:
            class AutogeneratedModelForm(forms.ModelForm):
                class Meta:
                    model = self._model
                    fields = '__all__'
            return AutogeneratedModelForm
        # TODO raise error
        print('Model or ModelFrom is Required. Please add it to {}'.format(self.__class__.__name__))

    def process_form_submission(self, form):
        form.save()
